{
    'name': 'CRM TikTok Lead Integration',
    'category': 'Social',
    'author': 'Pragmatic TechSoft Pvt Ltd.',
    'website': 'www.pragtech.co.in',
    'summary': 'Crm odoo dashboard social media facebook instagram linkedin twitter google adwords tik tok campaigns facebook forms lead generation capture leads ad campaigns lead forms lead import dynamic dashboard Odoo CRM Social Media Lead Form Ads Campaign Integration App',
    'version': '17.0',
    'description': 'Sync TikTok Leads with Odoo CRM',
    'depends': ['crm', 'utm', 'odoo_lead_forms_ad_integration_hub_crm'],
    'data': [
        'security/ir.model.access.csv',
        'data/tiktok_socail_dashboard_data.xml',
        'views/tiktok_menu_view.xml',
        'views/tiktok_res_config_settings_views.xml',
        'views/tiktok_social_media_view.xml',
        'views/tiktok_social_account_view.xml',
        'views/tiktok_lead_view.xml',
    ],
    'images': ['static/description/pragtech_crm_tiktok_leads.gif'],
    # 'images': ['static/description/end-of-year-sale-main.jpg'],
    'live_test_url': 'https://www.pragtech.co.in/company/proposal-form.html?id=103&name=crm-facebook-leads',
    'license': 'OPL-1',
    'price': 200.0,
    'currency': 'USD',
    'auto_install': False,
    'license': 'OPL-1',
    'auto_install': False,
}
